stolostron/multicloud-operators-foundation

Dockerfile
deploy/foundation/klusterlet/resources/agent-manifestwork.yaml

https://github.com/open-cluster-management/backlog/issues/4530

foundation need run as user instead of root

---

pkg/klusterlet/clusterinfo/clusterinfo_controller.go

related issue: https://github.com/open-cluster-management/backlog/issues/4214

fix wrong kubeVendor on Azure

---

pkg/klusterlet/agent/server.go

issue: https://github.com/open-cluster-management/backlog/issues/4998

speicify the minversion of tls

---

Makefile
deploy/foundation/hub/resources/crds/internal.open-cluster-management.io_managedclusterinfos.yaml
pkg/apis/internal.open-cluster-management.io/v1beta1/clusterinfo_types.go
pkg/controllers/autodetect/autodetect_controller.go
pkg/controllers/autodetect/autodetect_controller_test.go
pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go
test/e2e/clusterinfos_test.go
test/e2e/util/util.go

task: https://github.com/open-cluster-management/backlog/issues/5021

add clusterID label for managedCluster

---

cmd/controller/app/server.go
cmd/webhook/app/options/options.go

issue: https://github.com/open-cluster-management/backlog/issues/4998

fix Remediate Static Scan Findings

---

cmd/agent/agent.go
cmd/agent/app/server.go
pkg/controllers/clusterset/syncclusterrolebinding/syncclusterrolebinding_controller.go

related issue: https://github.com/open-cluster-management/backlog/issues/4998

fix gosec scan findings

---

deploy/foundation/hub/resources/clusterrole.yaml

https://github.com/open-cluster-management/backlog/issues/5664

Allow setting ownerref to secret from bma

---

pkg/klusterlet/view/view_controller.go
pkg/klusterlet/view/view_controller_test.go

https://github.com/open-cluster-management/backlog/issues/5554

Do not allow secret to be viewed

---

pkg/controllers/inventory/inventory_controller.go

relates to https://github.com/open-cluster-management/backlog/issues/5664

Fix bma status when using patch in syncset

---

cmd/agent/agent.go
cmd/controller/app/server.go

related issue: https://github.com/open-cluster-management/backlog/issues/7009

Use null logger to require less memory

---

pkg/controllers/clusterinfo/clusterinfo_controller.go

This reverts commit 57839edaaa506d5f4f0cb3b9b12cf7237dceb9b3.

Revert "remove cluster conditions in clusterinfo"

---

pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go

issue: https://github.com/open-cluster-management/backlog/issues/6965

check ocp311 version

---

pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go

task: https://github.com/open-cluster-management/backlog/issues/8114
add 2 claims:
1. region.open-cluster-management.io,  the region for OCP on AWS and GCP.
2. infrastructure.openshift.io , the infrastructure config of OCP, format {"infraName":"xxx"}

add claims for submariner

---

README.md

I've tried to compile all this and I've got bit by this. I know it's very minor stuff but it may help.
@cdoan1 FYI

To improve dev experience: gopath bin in path

---

pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go

related issue: https://github.com/open-cluster-management/backlog/issues/6965

show OpenShift 3

---

pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go

related issue: https://github.com/open-cluster-management/backlog/issues/8151

update the UpgradeFail defination

---

go.mod
go.sum
vendor/modules.txt

https://github.com/open-cluster-management/backlog/issues/8383

upgrade go-slug

---

pkg/apis/internal.open-cluster-management.io/v1beta1/clusterinfo_types.go
pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go

related issue: https://github.com/open-cluster-management/backlog/issues/8824

add vsphere cloud vendor detection

---

pkg/apis/internal.open-cluster-management.io/v1beta1/clusterinfo_types.go
pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go

related issue https://github.com/open-cluster-management/backlog/issues/8882

add openstack cloud vendor detection

---

deploy/foundation/hub/resources/clusterrole.yaml
pkg/controllers/inventory/inventory_controller.go
pkg/controllers/inventory/inventory_controller_test.go
test/e2e/inventory_test.go

https://github.com/open-cluster-management/backlog/issues/8971

Fix inventory

---

pkg/apis/internal.open-cluster-management.io/v1beta1/clusterinfo_types.go
pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go

related issue:  https://github.com/open-cluster-management/backlog/issues/8841

detect OSD cluster

---

pkg/controllers/autodetect/autodetect_controller.go
pkg/controllers/autodetect/autodetect_controller_test.go

relates to https://github.com/open-cluster-management/backlog/issues/9688.

Fix osd labels

---

pkg/controllers/inventory/inventory_controller.go

issue: https://github.com/open-cluster-management/backlog/issues/9463

fix issue that only updates status timestamps

---

pkg/proxyserver/cache/clusterview.go
pkg/proxyserver/cache/managedcluster_test.go
pkg/proxyserver/rest/managedcluster/managedcluster.go
pkg/proxyserver/rest/managedclusterset/managedclusterset.go

fix issue that cannot get clusterview resources using verb *
fix typo

fix issue that cannot get clusterview using verb *

---

.travis.yml
pkg/controller/inventory/inventory_controller.go
pkg/controller/inventory/inventory_controller_test.go

https://github.com/open-cluster-management/backlog/issues/10009

Fix inventory status wrong report

---

cmd/webhook/app/start.go
go.mod
pkg/webhook/useridentity/mutatingWebhook.go
pkg/webhook/useridentity/mutatingWebhook_test.go
vendor/modules.txt

1. decode object raw using Unstructured
2. fix AdmissionReview Kind and APIVersion is null after upgrade to v1
3. move the mutating webhook server to `pkg/webhook`

fix webhook issues

---

cmd/controller/app/server.go
pkg/controllers/clusterrole/clusterrole_controller.go
pkg/controllers/clusterset/clusterrole/clusterrole_controller.go
pkg/controllers/clusterset/clusterrole/clusterrole_controller_test.go
pkg/controllers/clusterset/clusterrole/rbac.go
pkg/utils/role.go
test/e2e/clusterset_test.go

https://github.com/open-cluster-management/backlog/issues/10680

Clusterset admin/view role

---

cmd/webhook/app/options/options.go
cmd/webhook/app/start.go
pkg/webhook/clusterset/validatingWebhook.go
pkg/webhook/clusterset/validatingWebhook_test.go

https://github.com/open-cluster-management/backlog/issues/12021

disable managedclusterset validating

---

pkg/controllers/clusterinfo/capacity_controller.go
pkg/controllers/clusterinfo/capacity_controller_test.go
pkg/klusterlet/nodecollector/nodecollecter.go
pkg/klusterlet/nodecollector/nodecollector_test.go
test/e2e/managedcluster_test.go

/hold
need to confirm with @itdove

Remove cpu_worker/socket etc

---

pkg/klusterlet/clusterinfo/clusterinfo_controller.go
test/e2e/clusterinfos_test.go
test/e2e/util/util.go

https://github.com/open-cluster-management/backlog/issues/12308

Fix nodelist bug

---

pkg/proxyserver/rest/managedcluster/managedcluster.go

story: https://github.com/open-cluster-management/backlog/issues/12424

add short name mcv for managedCluster.clusterview

---

pkg/proxyserver/printers/internalversion/printers.go
pkg/proxyserver/printers/internalversion/printers_test.go
pkg/proxyserver/printers/storage/storage.go
pkg/proxyserver/printers/tablegenerator.go
pkg/proxyserver/printers/tablegenerator_test.go
pkg/proxyserver/rest/managedcluster/managedcluster.go
vendor/k8s.io/apimachinery/pkg/util/duration/duration.go
vendor/modules.txt

the results of printer
```
$ oc get mcv
NAME       HUB ACCEPTED   MANAGED CLUSTER URLS   JOINED   AVAILABLE   AGE
cluster1   true           https://localhost      True     True        2d11h
[centos@yzw ~]$ oc get mcv cluster1
NAME       HUB ACCEPTED   MANAGED CLUSTER URLS   JOINED   AVAILABLE   AGE
cluster1   true           https://localhost      True     True        2d11h
```

add printer for managedcluster.clusterview

---

deploy/foundation/hub/resources/crds/internal.open-cluster-management.io_managedclusterinfos.yaml
pkg/apis/internal.open-cluster-management.io/v1beta1/clusterinfo_types.go
pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go

issue: https://github.com/open-cluster-management/backlog/issues/12519

add desired of ocp into clusterinfo.status

---

cmd/controller/app/server.go
cmd/webhook/app/options/options.go
cmd/webhook/app/start.go
pkg/webhook/clusterset/validatingWebhook.go
pkg/webhook/clusterset/validatingWebhook_test.go

https://github.com/open-cluster-management/backlog/issues/12053

update webhook qps and burst

---

pkg/controllers/clusterinfo/autodetect_controller.go
pkg/controllers/clusterinfo/autodetect_controller_test.go

https://github.com/open-cluster-management/backlog/issues/12633

add ocp version to managedcluster label

---

cmd/agent/agent.go
pkg/apis/internal.open-cluster-management.io/v1beta1/clusterinfo_types.go
pkg/controllers/clusterinfo/autodetect_controller.go
pkg/controllers/clusterinfo/autodetect_controller_test.go
pkg/klusterlet/clusterclaim/clusterclaim_controller.go
pkg/klusterlet/clusterclaim/clusterclaim_controller_test.go
pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go

story: https://github.com/open-cluster-management/backlog/issues/11779

sync labels to claims

---

Dockerfile
test/e2e/e2e_suite_test.go
test/e2e/util/util.go

Signed-off-by: hchenxa <huichen@redhat.com>
The PR used to generate the junit result when we set the environment variable `JUNIT_REPORT_FILE` exported.

enable the junit report

---

test/e2e/clusterset_test.go
test/e2e/e2e_suite_test.go
test/e2e/util/template.go
test/e2e/util/util.go

https://github.com/open-cluster-management/backlog/issues/12002

add more cases for clusterset rbac e2e

---

pkg/utils/role.go
pkg/utils/role_test.go

https://github.com/open-cluster-management/backlog/issues/13014

fix clusterset rbac

---

pkg/controllers/clusterset/clusterclaim/clusterclaim_controller.go
pkg/controllers/clusterset/clusterclaim/clusterclaim_controller_test.go
pkg/controllers/clusterset/clusterdeployment/clusterdeployment_controller.go
pkg/controllers/clusterset/clusterdeployment/clusterdeployment_controller_test.go
test/e2e/clusterset_test.go
test/e2e/util/template.go

https://github.com/open-cluster-management/backlog/issues/13011

fix claimed cluster can not delete from clusterset

---

pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go
pkg/klusterlet/nodecollector/nodecollecter.go
pkg/klusterlet/nodecollector/nodecollector_test.go

related issue: https://github.com/open-cluster-management/backlog/issues/12991

reduce clusterinfo update

---

cmd/agent/agent.go
cmd/agent/app/options/options.go
pkg/utils/rest/kubecontrol.go

https://github.com/open-cluster-management/backlog/issues/12579

add qps and burst for agent

---

pkg/klusterlet/clusterclaim/clusterclaim_controller.go
pkg/klusterlet/clusterclaim/clusterclaim_controller_test.go
pkg/klusterlet/clusterclaim/clusterclaimer.go
test/e2e/clusterclaim_test.go
test/e2e/clusterview_test.go
test/e2e/util/managedcluster.go

issue: https://github.com/open-cluster-management/backlog/issues/13368

fix delete customized clusterClaim

---

cmd/agent/agent.go
cmd/agent/app/options/options.go
deploy/managedcluster/hub/install.sh
deploy/managedcluster/klusterlet/install.sh
pkg/utils/rest/mapper.go

https://github.com/open-cluster-management/backlog/issues/12776

update qps and burst for agent

---

cmd/agent/agent.go
deploy/managedcluster/hub/install.sh
deploy/managedcluster/klusterlet/install.sh
go.mod
go.sum
vendor/github.com/open-cluster-management/addon-framework/pkg/lease/lease_controller.go
vendor/modules.txt

The related issue: https://github.com/open-cluster-management/backlog/issues/13338

lease compatible

---

pkg/apis/inventory/v1alpha1/baremetalasset_types.go
pkg/controllers/inventory/inventory_controller.go

https://github.com/open-cluster-management/backlog/issues/13514

create const to contain BMA status reason

---

cmd/webhook/app/options/options.go
cmd/webhook/app/start.go
pkg/webhook/useridentity/mutatingWebhook.go
pkg/webhook/useridentity/mutatingWebhook_test.go

https://github.com/open-cluster-management/backlog/issues/9533
Signed-off-by: Philip Wu <phwu@redhat.com>

Skip updating user and group ID for appsubs

---

cmd/controller/app/server.go
pkg/controllers/gc/garbagecollector_controller.go
pkg/controllers/gc/garbagecollector_controller_test.go

https://github.com/open-cluster-management/backlog/issues/13670

handle upgrade from 2.2.X to 2.3 to remove finalizer in clusterrole

---

deploy/foundation/hub/kustomization.yaml
deploy/foundation/hub/resources/clusterviewv1-apiservice.yaml
deploy/foundation/hub/resources/clusterviewv1alpha1-apiservice.yaml
deploy/foundation/hub/resources/controller.yaml
deploy/foundation/hub/resources/proxyserver-apiservice.yaml
deploy/foundation/hub/resources/proxyserver-service.yaml
deploy/foundation/hub/resources/proxyserver.yaml
deploy/foundation/hub/resources/webhook/kustomization.yaml
deploy/foundation/hub/resources/webhook/webhook-service.yaml
deploy/foundation/hub/resources/webhook/webhook-validating-config.yaml
deploy/foundation/hub/resources/webhook/webhook.yaml
deploy/foundation/klusterlet/kustomization.yaml
deploy/foundation/klusterlet/resources/agent-manifestwork.yaml
deploy/foundation/scripts/install-check.sh
test/e2e/actions_test.go
test/e2e/clusterclaim_test.go
test/e2e/clusterinfos_test.go
test/e2e/clusterset_test.go
test/e2e/clusterview_test.go
test/e2e/e2e_suite_test.go
test/e2e/inventory_test.go
test/e2e/lease_test.go
test/e2e/log_test.go
test/e2e/managedcluster_test.go
test/e2e/util/hive.go
test/e2e/util/rbac.go
test/e2e/util/template.go
test/e2e/views_test.go
test/e2e/webhook_test.go

issue: https://github.com/open-cluster-management/backlog/issues/13548

refactor e2e

---

pkg/controllers/clusterinfo/clusterinfo_controller.go
pkg/controllers/clusterinfo/clusterinfo_controller_test.go
pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go
pkg/klusterlet/nodecollector/nodecollecter.go
pkg/klusterlet/nodecollector/nodecollector_test.go
pkg/utils/utils.go

related issue: https://github.com/open-cluster-management/backlog/issues/13596

empty cluster status when cluster is offline

---

pkg/klusterlet/nodecollector/nodecollecter.go

issue: https://github.com/open-cluster-management/backlog/issues/13998

fix cert pool mem leak

---

cmd/agent/agent.go
cmd/controller/app/server.go
deploy/foundation/hub/resources/crds/internal.open-cluster-management.io_managedclusterinfos.yaml
pkg/apis/internal.open-cluster-management.io/v1beta1/clusterinfo_types.go
pkg/controllers/clusterca/clusterca_controller.go
pkg/controllers/clusterca/clusterca_controller_test.go
pkg/controllers/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go
pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go
pkg/utils/clusterca.go
pkg/utils/clusterca_test.go

https://github.com/open-cluster-management/backlog/issues/14136

Clusterca info

---

pkg/klusterlet/clusterclaim/clusterclaimer.go

issue :  https://github.com/open-cluster-management/backlog/issues/14691

fix wrong platform

---

deploy/managedcluster/klusterlet/install.sh
pkg/klusterlet/clusterclaim/clusterclaimer.go

fix issue: https://github.com/open-cluster-management/backlog/issues/14691

[release-2.3] fix wrong platform

---

go.mod
go.sum
vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
vendor/github.com/openshift/hive/apis/hive/v1/clusterclaim_types.go
vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
vendor/modules.txt

https://github.com/open-cluster-management/backlog/issues/15987

upgrade hive to 1.1.16

---

go.mod
go.sum
vendor/github.com/openshift/hive/apis/hive/v1/azure/platform.go
vendor/github.com/openshift/hive/apis/hive/v1/clusterdeprovision_types.go
vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
vendor/modules.txt

https://github.com/open-cluster-management/backlog/issues/16552

upgrade hive api

---

pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go

issue: https://github.com/open-cluster-management/backlog/issues/17690

fix the issue that to get wrong ocp version

---

pkg/webhook/clusterset/validatingWebhook.go
pkg/webhook/serve/serve.go
pkg/webhook/serve/serve_test.go
pkg/webhook/useridentity/mutatingWebhook.go
pkg/webhook/useridentity/mutatingWebhook_test.go

[#17766](https://github.com/open-cluster-management/backlog/issues/17766)

handle request error in webhook

---

pkg/klusterlet/clusterclaim/clusterclaimer.go

fix issue: https://github.com/open-cluster-management/backlog/issues/18477

fix the issue failed to get infra in ocp311

---

Makefile
README.md

update the guide on how to deploy and clean up

---

pkg/klusterlet/clusterclaim/clusterclaimer.go

task: https://github.com/stolostron/backlog/issues/18513

add exclude backup label for clusterclaims

---

pkg/webhook/clusterset/validatingWebhook.go
pkg/webhook/clusterset/validatingWebhook_test.go

https://github.com/stolostron/backlog/issues/20121

ignore ai created clusterdeployment permission check

---

pkg/klusterlet/clusterclaim/clusterclaimer.go

fix product cannot be updated in ocp upgrade failure case

---

deploy/managedcluster/hub/install.sh
deploy/managedcluster/klusterlet/install.sh

deploy release 2.4 OCM for 2.4 branch

---

pkg/helpers/clustersetmapper.go
pkg/helpers/clustersetmapper_test.go

https://github.com/stolostron/backlog/issues/20670

fix rbac about generate rolebinding for clusterset

---

pkg/apis/internal.open-cluster-management.io/v1beta1/clusterinfo_types.go
pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go
pkg/klusterlet/clusterinfo/clusterinfo_controller.go

task: https://github.com/stolostron/backlog/issues/20613

support to detect RHV, AlibabaCloud and BareMetal for OCP

---

pkg/addon/addon_test.go
pkg/addon/manifests/chart/templates/service.yaml

fix addon service type

---

pkg/addon/addon.go
pkg/addon/addon_test.go
pkg/addon/manifests/chart/templates/deployment.yaml
pkg/addon/manifests/chart/templates/route.yaml
pkg/addon/manifests/chart/templates/service.yaml
pkg/addon/manifests/chart/values.yaml

issue:  https://github.com/stolostron/backlog/issues/21554

fix the addon is  failed to deploy on OCP311

---

pkg/controllers/inventory/deleting_clusterdeployment_controller.go
pkg/controllers/inventory/deleting_clusterdeployment_controller_test.go
pkg/controllers/inventory/inventory_controller.go
pkg/controllers/inventory/inventory_controller_test.go

Signed-off-by: Jian Qiu <jqiu@redhat.com>

Add backup label

---

pkg/helpers/imageregistry/client.go
pkg/helpers/imageregistry/client_test.go
test/e2e/e2e_suite_test.go
test/e2e/util/util.go

fix empty imageregistries annotation

---

pkg/helpers/imageregistry/client.go
pkg/helpers/imageregistry/client_test.go
pkg/helpers/imageregistry/defaultclient.go
pkg/helpers/imageregistry/defaultclient_test.go

add back the imageregistry defaultclient to be compatible with old user

revert imageregistry defaultclient to be compatible with old user

---

go.mod
go.sum
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/addoninstall/controller.go

fix issue: https://github.com/stolostron/backlog/issues/21852

upgrade addon-framework

---

.gitignore

reference issue: https://github.com/stolostron/backlog/issues/22156

Ignore vscode to trigger ci

---

pkg/webhook/clusterset/validatingWebhook.go

https://github.com/stolostron/backlog/issues/22227#event-6553624161

allow claimed cluster move to default set

---

pkg/webhook/clusterset/validatingWebhook_test.go

add test for cluster from clusterpool

---

deploy/managedcluster/hub/install.sh
deploy/managedcluster/klusterlet/install.sh

[release-2.2] Add env for registration operator branch

---

deploy/managedcluster/hub/install.sh
deploy/managedcluster/klusterlet/install.sh

[release-2.3] Add env for registration operator branch

---

deploy/managedcluster/hub/install.sh
deploy/managedcluster/klusterlet/install.sh

[release-2.4] Add env for registration operator branch

---

.gitignore

issue reference: https://github.com/stolostron/backlog/issues/22156

[release-2.2] Ignore vscode to trigger ci

---

pkg/webhook/clusterset/validatingWebhook.go
pkg/webhook/clusterset/validatingWebhook_test.go

https://github.com/stolostron/backlog/issues/22227
related pr in main branch:
https://github.com/stolostron/multicloud-operators-foundation/pull/471
https://github.com/stolostron/multicloud-operators-foundation/pull/477

fix claimed cluster add default set

---

cmd/agent/agent.go

run the health server before newManager

---

pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go

The related issue: https://github.com/stolostron/backlog/issues/23099

transform label key to valid resource name

---

deploy/foundation/hub/resources/crds/inventory.open-cluster-management.io_baremetalassets.crd.yaml
go.mod
go.sum
vendor/github.com/stolostron/cluster-lifecycle-api/inventory/v1alpha1/inventory.open-cluster-management.io_baremetalassets.crd.yaml
vendor/modules.txt

https://github.com/stolostron/backlog/issues/24149

deprecate bm asset

---

pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go

issue: https://github.com/stolostron/backlog/issues/24289

get region from nodes

---

pkg/webhook/clusterset/validatingWebhook.go

https://github.com/stolostron/backlog/issues/24286

do not allow to update global clusterset

---

pkg/klusterlet/clusterclaim/clusterclaim_controller.go
pkg/klusterlet/clusterclaim/clusterclaim_controller_test.go
pkg/klusterlet/clusterclaim/clusterclaimer.go
test/e2e/clusterclaim_test.go

https://github.com/stolostron/backlog/issues/23826

Add consist list for clusterclaims

---

cmd/agent/agent.go
cmd/agent/app/options/options.go
pkg/addon/addon.go
pkg/addon/addon_test.go
pkg/addon/manifests/chart/templates/deployment.yaml
pkg/addon/manifests/chart/values.yaml
pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go

Relate issue: https://github.com/stolostron/backlog/issues/23826

Add an option to control `sync labels to clusterclaims`

---

pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go

https://github.com/stolostron/backlog/issues/23826

Change managedcluster name to uid of kube-system ns uid

---

cmd/agent/agent.go
cmd/agent/app/options/options.go
pkg/addon/addon.go
pkg/addon/manifests/chart/templates/deployment.yaml
pkg/addon/manifests/chart/values.yaml

https://github.com/stolostron/backlog/issues/23826

Add flag to control nodeCollector

---

cmd/agent/agent.go
cmd/agent/app/options/options.go
pkg/addon/addon.go
pkg/addon/manifests/chart/templates/deployment.yaml
pkg/addon/manifests/chart/values.yaml
pkg/klusterlet/nodecollector/nodecollecter.go
pkg/klusterlet/nodecollector/nodecollector_test.go

Fix: only disable capacity in hosted mode addon

---

pkg/controllers/clusterset/globalclusterset/globalset_controller.go
pkg/controllers/clusterset/globalclusterset/globalset_controller_test.go
test/e2e/clusterset_test.go

https://github.com/stolostron/backlog/issues/24532

check cluster-manager exist when apply global set ns

---

pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go

Signed-off-by: Wei Liu <liuweixa@redhat.com>

detecting roks

---

pkg/klusterlet/clusterclaim/clusterclaim_controller.go
pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go

issue: https://github.com/stolostron/backlog/issues/25185

use restmapper to check ocp and do not delete version claim

---

go.mod
go.sum
pkg/controllers/clusterinfo/autodetect_controller.go
pkg/controllers/clusterinfo/autodetect_controller_test.go
vendor/github.com/stolostron/cluster-lifecycle-api/clusterinfo/v1beta1/types.go
vendor/modules.txt

add two more labels for ocp version

---

pkg/controllers/clusterinfo/autodetect_controller.go
pkg/controllers/clusterinfo/autodetect_controller_test.go

The related issue: https://github.com/stolostron/backlog/issues/26401

handle ocp 311 case when adding major-minor label

---

Dockerfile
go.mod

Bump go version to 1.19

---

pkg/controllers/clusterinfo/autodetect_controller.go
pkg/controllers/clusterinfo/autodetect_controller_test.go

The related issues: 
- https://issues.redhat.com/browse/ACM-2019
- https://issues.redhat.com/browse/ACM-2013

support ocp dev version

---

cmd/controller/app/server.go
go.mod
go.sum
pkg/addon/addon_test.go
pkg/addon/manifests/chart/templates/namespace.yaml
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/addondeploymentconfig.go
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/helm_agentaddon.go
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/template_agentaddon.go
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/testmanifests/chart/templates/clusterclaim.yaml
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/testmanifests/template/clusterclaim.yaml
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/constants/constants.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/utils.go

The related issue: https://github.com/stolostron/backlog/issues/26725

make managed kubeconfig secret name configurable

---

cmd/controller/app/server.go
pkg/controllers/addoninstall/addon_install_controller.go
pkg/controllers/addoninstall/addon_install_controller_test.go
test/e2e/addoninstall_test.go

The related issue: https://github.com/stolostron/backlog/issues/26723

install work-manager outside of addon manager

---

test/e2e/clusterset_test.go

https://github.com/stolostron/backlog/issues/25657

add clusterset e2e

---

go.mod
go.sum
pkg/addon/manifests/chart/templates/namespace.yaml
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/constants/constants.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/clustermanagement/controller.go

The related issue: https://issues.redhat.com/browse/ACM-2290

fix annotation typo

---

pkg/klusterlet/clusterclaim/clusterclaim_controller.go
pkg/klusterlet/clusterclaim/clusterclaim_controller_test.go
pkg/klusterlet/clusterclaim/clusterclaimer.go

issue :  https://issues.redhat.com/browse/ACM-2998

update id.k8s.io claim if empty

---

cmd/agent/agent.go
cmd/agent/app/options/options.go
cmd/controller/controller.go
cmd/proxyserver/proxyserver.go
cmd/webhook/webhook.go

Fix: klog log verbosity.

---

cmd/controller/app/server.go
pkg/controllers/clusterset/syncclusterrolebinding/syncclusterrolebinding_controller.go
pkg/controllers/clusterset/syncclusterrolebinding/syncclusterrolebinding_controller_test.go
pkg/controllers/clusterset/syncrolebinding/syncrolebinding_controller.go
pkg/controllers/clusterset/syncrolebinding/syncrolebinding_controller_test.go
pkg/utils/role.go
pkg/utils/role_test.go

fix issue about clusterrolebinding/rolebinding clusterset label

---

pkg/controllers/clusterca/clusterca_controller.go
pkg/controllers/clusterca/clusterca_controller_test.go

issue reference: https://issues.redhat.com/browse/ACM-2094

prepend the new managed cluster client config

---

cmd/webhook/app/start.go
pkg/webhook/mutating/admission.go
pkg/webhook/mutating/webhook.go
pkg/webhook/mutating/webhook_test.go
pkg/webhook/serve/serve.go
pkg/webhook/validating/webhook.go
pkg/webhook/validating/webhook_test.go

Refactor the webhooks:
- rename the package and file names
- validating by resources

refactor clusterset validating webhook

---

test/e2e/managedcluster_test.go

https://github.com/stolostron/backlog/issues/25657

add test case about cluster clusterrole

---

pkg/controllers/clusterinfo/capacity_controller.go
pkg/controllers/clusterinfo/capacity_controller_test.go

issue: https://issues.redhat.com/browse/ACM-3464

fix to get cores of SNO cluster

---

cmd/controller/app/options/options.go
cmd/controller/app/server.go

Reverts stolostron/multicloud-operators-foundation#577

Revert "set leader election options"

---

Makefile
deploy/foundation/hub/resources/webhook-validating-config.yaml
pkg/constants/constants.go
pkg/webhook/validating/webhook.go
pkg/webhook/validating/webhook_test.go
test/integration-test.mk
test/integration/suite_test.go
test/integration/webhook_test.go

If there is any hypershift hosted cluster running on the cluster deployment, it is not allowed to delete

Validate cluster deployment delete request

---

pkg/addon/addon.go
pkg/addon/addon_test.go

issue :https://issues.redhat.com/browse/ACM-4638

fix work-manager route is not created on ARO

---

pkg/addon/addon.go
pkg/addon/addon_test.go
pkg/addon/manifests/chart/templates/deployment.yaml
pkg/addon/manifests/chart/templates/route.yaml
pkg/addon/manifests/chart/templates/service.yaml
pkg/klusterlet/clusterinfo/clusterinfo_controller.go

issue : https://issues.redhat.com/browse/ACM-4652

do not create route in hosted mode

---

pkg/addon/manifests/chart/templates/deployment.yaml

https://issues.redhat.com/browse/ACM-4546

add securityContext in klusterlet agent

---

pkg/addon/manifests/chart/templates/deployment.yaml

Reverts stolostron/multicloud-operators-foundation#586

Revert "add securityContext in klusterlet agent"

---

cmd/agent/app/server.go
cmd/proxyserver/app/options/options.go
cmd/webhook/app/options/options.go
pkg/klusterlet/agent/server.go
pkg/klusterlet/nodecollector/nodecollecter.go

Fixes:
* https://issues.redhat.com/browse/ACM-5220 - ocm-proxyserver
* https://issues.redhat.com/browse/ACM-5221 - ocm-webhook
* https://issues.redhat.com/browse/ACM-5239 - klusterlet-addon-workmgr

Update to TLS1.3

---

deploy/foundation/hub/resources/crds/internal.open-cluster-management.io_managedclusterinfos.crd.yaml
go.mod
go.sum
pkg/controllers/clusterca/clusterca_controller.go
pkg/controllers/clusterca/clusterca_controller_test.go
pkg/klusterlet/clusterinfo/distributionInfo_sync.go
pkg/klusterlet/clusterinfo/distributionInfo_sync_test.go
vendor/github.com/stolostron/cluster-lifecycle-api/clusterinfo/v1beta1/internal.open-cluster-management.io_managedclusterinfos.crd.yaml
vendor/github.com/stolostron/cluster-lifecycle-api/clusterinfo/v1beta1/types.go
vendor/github.com/stolostron/cluster-lifecycle-api/clusterinfo/v1beta1/zz_generated.swagger_doc_generated.go
vendor/modules.txt

issue reference: https://issues.redhat.com/browse/ACM-4647

replace the last applied managed cluster api server url when it changes

---

deploy/foundation/hub/resources/clusterrole.yaml
test/e2e/clusterinfos_test.go
test/e2e/managedcluster_test.go

fix issue : https://github.com/stolostron/backlog/issues/27280

add patch mcl rbac and e2e

---

pkg/controllers/clusterinfo/autodetect_controller.go
pkg/controllers/clusterinfo/autodetect_controller_test.go

issue: https://issues.redhat.com/browse/ACM-5454

exclude labels on managedClusterInfo

---

pkg/addon/manifests/chart/templates/deployment.yaml

https://issues.redhat.com/browse/ACM-5018

fix security contex issue in mcee2.2

---

cmd/agent/app/server.go
cmd/proxyserver/app/options/options.go
cmd/webhook/app/options/options.go
pkg/klusterlet/agent/server.go
pkg/klusterlet/nodecollector/nodecollecter.go

Fix https://access.redhat.com/security/cve/CVE-2023-3089

downgrade min TLS version to 1.2

---

Makefile

fix issue: https://access.redhat.com/security/cve/CVE-2023-3089

explicitly enable CGO

---

pkg/controllers/imageregistry/imageregistry_controller.go

reduce error logs since there is a case that there is no placement label in placementdecision.

reduce error logs

---

cmd/controller/app/options/options.go
cmd/controller/app/server.go
pkg/addon/addon.go
pkg/addon/addon_test.go
pkg/utils/clusterset/clusterset.go
pkg/utils/clusterset/clusterset_test.go
pkg/utils/role.go
pkg/utils/role_test.go

Also add a flag to disable rbac optionally

Use rolebinding informer when apply rolebinding

---

cmd/proxyserver/app/start.go
pkg/proxyserver/controller/controller.go
pkg/proxyserver/controller/controller_test.go

issue: https://issues.redhat.com/browse/ACM-6288

filter configmap in proxyserver

---

go.mod
go.sum
pkg/controllers/clusterinfo/autodetect_controller.go
pkg/controllers/clusterinfo/autodetect_controller_test.go
pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go
pkg/klusterlet/clusterinfo/defaultInfo_sync.go
vendor/github.com/stolostron/cluster-lifecycle-api/clusterinfo/v1beta1/types.go
vendor/modules.txt

story: https://issues.redhat.com/browse/ACM-6849

auto detect microshift

---

pkg/klusterlet/clusterclaim/clusterclaimer.go

Fixes: https://issues.redhat.com/browse/ACM-7408

Fix: missing clusterclaim.

---

pkg/klusterlet/clusterclaim/clusterclaimer_test.go

Fixes: https://issues.redhat.com/browse/ACM-7408

Add: U-T for clusterclaim sync function.

---

pkg/klusterlet/view/view_controller_test.go
pkg/utils/rest/kubecontrol.go

fixes: https://issues.redhat.com/browse/ACM-7479

Fix: return origin error when it mapping fails.

---

cmd/agent/agent.go
pkg/klusterlet/clusterclaim/clusterclaim_controller.go
pkg/klusterlet/clusterclaim/clusterclaim_controller_test.go
pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go
pkg/klusterlet/clusterclaim/manager.go
pkg/klusterlet/clusterinfo/manager.go

This is a backport of https://github.com/stolostron/multicloud-operators-foundation/pull/662
Fixes:
* https://issues.redhat.com/browse/ACM-7497
* https://issues.redhat.com/browse/ACM-7762

Refactor: fix klusterlet claims problems.

---

cmd/agent/agent.go
pkg/klusterlet/clusterclaim/clusterclaim_controller.go
pkg/klusterlet/clusterclaim/clusterclaim_controller_test.go
pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go
pkg/klusterlet/clusterclaim/manager.go
pkg/klusterlet/clusterinfo/controller.go

This is a backport of https://github.com/stolostron/multicloud-operators-foundation/pull/662
Fixes:
* https://issues.redhat.com/browse/ACM-7497
* https://issues.redhat.com/browse/ACM-7762

Refactor clusterclaim on 2.3.

---

.tekton/multicloud-manager-pull-request.yaml
.tekton/multicloud-manager-push.yaml
Dockerfile.rhtap

related issue: https://issues.redhat.com/browse/ACM-7262

add dockerfile for rhtap

---

test/e2e/e2e_suite_test.go
test/e2e/managedcluster_test.go
test/e2e/util/util.go

issue reference: https://github.com/stolostron/multicloud-operators-foundation/issues/680

[bp-2.3] stop running get ca from service account test for ocp 1.24 or above

---

test/e2e/managedcluster_test.go
test/e2e/webhook_test.go

issue reference:
- https://github.com/stolostron/multicloud-operators-foundation/issues/684
- https://github.com/stolostron/multicloud-operators-foundation/issues/686

[bp-2.2] Comment out tests that may cause ocp api server to degrade

---

pkg/controllers/clusterinfo/capacity_controller.go
pkg/controllers/clusterinfo/capacity_controller_test.go

issue： https://issues.redhat.com/browse/ACM-4537

[backplane-2.2]cherry-pick update the criteria for determining worker nodes

---

pkg/klusterlet/nodecollector/nodecollecter.go

Fixes: https://issues.redhat.com/browse/ACM-8681

Fix: add topology region zone.

---

test/e2e/e2e_suite_test.go
test/e2e/managedcluster_test.go
test/e2e/util/util.go

issue reference: https://github.com/stolostron/multicloud-operators-foundation/issues/680

stop running get ca from service account test for ocp 1.24 or above

---

cmd/agent/agent.go
pkg/klusterlet/clusterclaim/clusterclaim_controller.go
pkg/klusterlet/clusterclaim/clusterclaim_controller_test.go
pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/manager.go
pkg/klusterlet/clusterclaim/schedulable.go
pkg/klusterlet/clusterinfo/manager.go
pkg/klusterlet/objectsource/clusterclaim.go
pkg/klusterlet/objectsource/node.go
sonar-project.properties

Fixes: https://issues.redhat.com/browse/ACM-4875

Add a new clusterclaim based on node schedulable status.

---

pkg/klusterlet/clusterclaim/clusterclaim_controller.go

Fixes: https://issues.redhat.com/browse/ACM-9688

Remove "hub-managed" from clusterclaim schedulable.

---

pkg/addon/manifests/chart/templates/deployment.yaml
pkg/addon/manifests/chart/templates/service_account.yaml

issue: https://issues.redhat.com/browse/ACM-9759

move imagepullsecret to sa from deployment

---

pkg/addon/manifests/chart/templates/deployment.yaml
pkg/addon/manifests/chart/templates/service_account.yaml

Reverts stolostron/multicloud-operators-foundation#715
fix issue https://issues.redhat.com/browse/ACM-10470

Revert "move imagepullsecret to sa from deployment"

---

.tekton/multicloud-manager-mce-25-pull-request.yaml
.tekton/multicloud-manager-mce-25-push.yaml

Related PR: https://github.com/stolostron/multicloud-operators-foundation/pull/722
Related doc: https://togithub.com/redhat-appstudio/build-definitions/blob/main/task/summary/0.2/MIGRATION.md

Migration task-summary from 0.1 to 0.2

---

pkg/controllers/imageregistry/imageregistry_controller.go
pkg/controllers/imageregistry/imageregistry_controller_test.go

issue: https://issues.redhat.com/browse/ACM-12243

do not remove imageregistry label and annotation if cluster is deleting

---

pkg/klusterlet/clusterclaim/clusterclaimer.go

issue: https://issues.redhat.com/browse/ACM-13342

fix the new claim deleted by old addon in HCP case

---

pkg/webhook/validating/webhook.go
pkg/webhook/validating/webhook_test.go
test/e2e/webhook_test.go

1. can only create one local-cluster
2. can not update local-cluster to non local-cluster

local-cluster webhook

---

pkg/addon/addon.go
pkg/addon/addon_test.go
pkg/addon/manifests/chart/templates/deployment.yaml

issue: https://issues.redhat.com/browse/ACM-14178

fix cannot override the addon values using customized variable

---

.tekton/multicloud-manager-mce-28-pull-request.yaml
.tekton/multicloud-manager-mce-28-push.yaml

This PR:
- Formatting all tekton files
- Update konflux CEL from backplane-2.8 to main

:seedling: [main] update konflux files

---

go.mod
go.sum
vendor/github.com/openshift/hive/apis/hive/v1/syncset_types.go
vendor/golang.org/x/net/html/doc.go
vendor/golang.org/x/net/html/doctype.go
vendor/golang.org/x/net/html/foreign.go
vendor/golang.org/x/net/html/iter.go
vendor/golang.org/x/net/html/node.go
vendor/golang.org/x/net/html/parse.go
vendor/golang.org/x/net/http2/client_conn_pool.go
vendor/golang.org/x/net/http2/config.go
vendor/golang.org/x/net/http2/config_go124.go
vendor/golang.org/x/net/http2/config_pre_go124.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/net/http2/unencrypted.go
vendor/golang.org/x/net/http2/write.go
vendor/golang.org/x/net/websocket/websocket.go
vendor/modules.txt

Upgrade hive apis to latest version in Train 23

Upgrade hive apis in Train 23

---

cmd/controller/app/server.go
pkg/controllers/hostedannotation/hosted_annotation_controller.go
pkg/controllers/hostedannotation/hosted_annotation_controller_test.go

https://issues.redhat.com/browse/ACM-15763
runbook: https://github.com/stolostron/foundation-docs/pull/6

🌱 Add debug logs for leader election

---

cmd/agent/agent.go

https://issues.redhat.com/browse/ACM-17811

Restart when the external managed kubeconfig changes

---

.tekton/multicloud-manager-mce-28-pull-request.yaml
.tekton/multicloud-manager-mce-28-push.yaml

This PR:
- Update konflux CEL from main to backplane-2.8

:seedling: [backplane-2.8] update konflux files

---

go.mod
vendor/modules.txt

The related issue: https://issues.redhat.com/browse/ACM-19453

[mce-2.4 ] fix CVE-2025-22869

---

pkg/proxyserver/rest/project/index.go
pkg/proxyserver/rest/project/index_test.go
pkg/proxyserver/rest/project/list.go
pkg/proxyserver/rest/project/rest.go

issue: https://issues.redhat.com/browse/ACM-21049

support subjects for clusterpermission

---

.tekton/multicloud-manager-mce-29-pull-request.yaml
.tekton/multicloud-manager-mce-29-push.yaml

This PR:
- Formatting all tekton files
- Update konflux CEL from main to backplane-2.9

:seedling: [backplane-2.9] update konflux files

---

.tekton/multicloud-manager-mce-210-push.yaml

This PR adds slack notification support for the multicloud-operators-foundation repository.

🌱 add slack notification for multicloud-operators-foundation

---

pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go

The related issue: https://issues.redhat.com/browse/ACM-22896

add Nutanix platform support
