stolostron/multicloud-operators-foundation

deploy/foundation/hub/resources/proxyserver.yaml
test/e2e/e2e_suite_test.go
test/e2e/util/util.go

1. fix proxyserver has no permission (non-root) to create dir when `make deploy-foundation-hub`
```
$ kubectl logs -n open-cluster-management acm-proxyserver-54d4f8c7b5-ng5fq
error creating self-signed certificates: mkdir apiserver.local.config: permission denied
```
2. add e2e case to check if pods of foundation are ready.

fix proxyserver has no permission to create dir

---

pkg/controllers/autodetect/autodetect_controller.go

fix that update clusterinfo labels constantly if the cluster and clusterinfo have no labels.
`clusterInfo.ObjectMeta.Labels == nil`, but `labels == map[string]string{} `
so `reflect.DeepEqual(labels, clusterInfo.ObjectMeta.Labels)` is always false.

fix that update clusterinfo labels constantly

---

pkg/klusterlet/clusterinfo/clusterinfo_controller.go

we cannot get ocp version in OCP 3.x, should ignore the NotFound error here for OCP 3.x.

ignoreNotFound error when get version in OCP3.x

---

pkg/controllers/clusterinfo/clusterinfo_controller.go

we can remove cluster conditions in clusterinfo since no components get cluster conditions from clusterinfo. 
Search is now getting the status conditions from ManagedCluster in this release (https://github.com/open-cluster-management/backlog/issues/3946)

remove cluster conditions in clusterinfo

---

pkg/controllers/inventory/inventory_controller.go

relates to https://github.com/open-cluster-management/backlog/issues/8044
This is to reduce the mem consumption in ocm-controller. We do not need this watch since if secret is not found for a bma, we always requeue.

Remove secret watch in inventory

---

deploy/foundation/hub/resources/clusterviewv1-apiservice.yaml
deploy/foundation/hub/resources/clusterviewv1alpha1-apiservice.yaml
pkg/controllers/clusterrole/rbac.go
pkg/proxyserver/cache/clusterview.go
pkg/proxyserver/cache/clusterview_test.go
pkg/proxyserver/cache/managedcluster_test.go
pkg/proxyserver/cache/rbac/allow.go
pkg/utils/role.go
test/e2e/clusterview_test.go

1. add clusterview rules into cluster admin/view clusterrole.
2. if user has  managedclustersets/join create role of a clusterset, add the user to the clusterset rolebinding to add cluster admin roles to the user.
3. user can only  get/list clusterview resources if user has get/list cluster roles.
4. add ut and fix e2e issue.

add clusterview rules to cluster admin and view roles

---

pkg/apis/internal.open-cluster-management.io/v1beta1/clusterinfo_types.go
pkg/klusterlet/clusterinfo/clusterinfo_controller.go
pkg/klusterlet/clusterinfo/clusterinfo_controller_test.go

show CloudLabel `IBM Power` for IBM power , `IBM Z` for IBM Z.
related issue: https://github.com/open-cluster-management/backlog/issues/8967

detect IBM power and z arch managedCluster

---

docs/proxyserver/proxyserver.md
pkg/proxyserver/controller/controller.go
pkg/proxyserver/controller/controller_test.go

ca.crt is removed from the search secret with cert manager removal
Based on this [doc]( https://docs.openshift.com/container-platform/4.1/authentication/certificates/service-serving-certificate.html#add-service-certi[…]rving-certificate), writing the ca.crt to a configmap and using that for connecting.
Also, to resolve canaries https://github.com/open-cluster-management/backlog/issues/11742

Search secret doesn't have ca.crt - use configmap

---

pkg/klusterlet/clusterclaim/clusterclaimer.go

SNO has no openshift-console,  to return error will break the other clusterClaims collecting.

fix no openshift console in SNO

---

cmd/controller/app/server.go
pkg/addon/addon.go
pkg/addon/addon_test.go

work-manager addon handles the image override and nodeSelector by itself.

fix addon image and nodeSelector override

---

pkg/addon/addon.go
pkg/addon/addon_test.go
pkg/addon/manifests/chart/templates/deployment.yaml
pkg/addon/manifests/chart/templates/route.yaml
pkg/addon/manifests/chart/templates/service.yaml
pkg/addon/manifests/chart/values.yaml
pkg/helpers/imageregistry/client.go
pkg/helpers/imageregistry/client_test.go
test/e2e/imageregistry_test.go

1. fix issue: https://github.com/stolostron/backlog/issues/21853
OCP 311 has route, support to get log using route.
2. fix issue: https://github.com/stolostron/backlog/issues/21554
work-agent cannot update service if the type of service is changed in OCP 311, and return error 
`invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'`
this is an issue in old k8s version,  has been fixed in new one. https://github.com/kubernetes/kubectl/issues/221
the fix in addon is that deploy service until the product claim has value. will not update it in addon manifestwork.
3. return error for the interface of the imageRegisty Client to help debug.

fix no route in ocp 311 and errors in log

---

deploy/managedcluster/hub/install.sh
deploy/managedcluster/klusterlet/install.sh

After this is merged, we can use prow config to `export REGISTRATION_OPERATOR_BRANCH` to control the OCM version.

Add env for registration operator branch

---

pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go

issue: https://issues.redhat.com/browse/ACM-2625

fix empty id.k8s.io in ocp311

---

pkg/controllers/clusterinfo/capacity_controller.go
pkg/controllers/clusterinfo/capacity_controller_test.go

core_worker and socket_worker are collected by acm_managed_cluster_info metric for billing, 
so need calculate all nodes where the workloads can be placed. so calculate the data from all nodes we can get .
story: https://issues.redhat.com/browse/ACM-3464

update the criteria for determining worker nodes

---

pkg/controllers/clusterinfo/capacity_controller.go
pkg/controllers/clusterinfo/capacity_controller_test.go
pkg/controllers/clusterinfo/clusterinfo_controller.go
test/e2e/clusterview_test.go

to avoid update conflict error  
```
{"level":"error","ts":"2023-05-11T09:37:31Z","msg":"Reconciler error","controller":"clustercapcity-controller","object":{"name":"hosted","namespace":"hosted"},"namespace":"hosted","name":"hosted","reconcileID":"45e79b82-0221-461b-be7a-7f40d17a3173","error":"ManagedCluster.cluster.open-cluster-management.io \"hosted\" is invalid: status.conditions: Invalid value: \"null\": status.conditions in body must be of type array: \"null\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/workspace/multicluster-controlplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/workspace/multi …
```

update cluster capacity only when cluster is available

---

pkg/klusterlet/clusterinfo/loggingInfo_sync.go

See this doc: https://docs.openshift.com/container-platform/4.12/networking/ingress-operator.html#nw-ingress-configuring-application-domain_configuring-ingress
If appsDomain is set, it should override whatever is set in `domain` when creating a Route.
This illustrates the problem:
```
[loganmc10@fedoralogan ~]$ oc get route -A
NAMESPACE                             NAME                       HOST/PORT                                                             PATH        SERVICES                   PORT    TERMINATION            WILDCARD
open-cluster-management-agent-addon   klusterlet-addon-workmgr   workmgr-f237a30cbe328fa345042ce3db57ffb5.apps.smb.bacoosta.com                    klusterlet-addon-workmgr   <all>   passthrough            None
openshift-authentication …
```

Use appsDomain if it is set when determining Route host

---

cmd/agent/agent.go
pkg/klusterlet/view/view_controller_test.go
vendor/k8s.io/client-go/discovery/cached/legacy.go
vendor/modules.txt

Fixes: https://issues.redhat.com/browse/ACM-7479
Root cause: Start with this [PR](https://github.com/kubernetes-sigs/controller-runtime/pull/2296), the behavior of `NewDynamicRESTMapper` changed.
Run this `restMapper.KindFor(&schema.GroupVersionResource{Resource:"deployment"}})`, the results:
Before it returns a `GroupVersionKind`:
```
schema.GroupVersionKind{ Group: "apps", Kind: "Deployment", Version: "v1"}
```
But now, it returns the error:
```
no matches for kind "deployment" in version ""
```
The root cause is in controller-runtime `v0.14.6`, it reloads by this function: https://github.com/kubernetes-sigs/controller-runtime/blob/cd65cb25d314f40a329a688f4714fe3282589e97/pkg/client/apiutil/dynamicrestmapper.go#L94 which caches all groups and resource from discoveryClient.
But after …

Fix: mapping failed.

---

cmd/agent/agent.go
go.mod
pkg/klusterlet/view/view_controller_test.go
pkg/utils/rest/reloadmapper.go
sonar-project.properties
test/e2e/clusterview_test.go
test/e2e/e2e_suite_test.go
test/e2e/util/util.go
test/e2e/views_test.go

fixes: https://issues.redhat.com/browse/ACM-7479
`DefferdDiscoveryRestMapper` requires explicily reload when`IsNotMatch` error occurs.

Fix: restmapping fail when new crd added.

---

cmd/agent/agent.go
pkg/klusterlet/clusterclaim/clusterclaim_controller.go
pkg/klusterlet/clusterclaim/clusterclaim_controller_test.go
pkg/klusterlet/clusterclaim/clusterclaimer.go
pkg/klusterlet/clusterclaim/clusterclaimer_test.go
pkg/klusterlet/clusterclaim/manager.go
pkg/klusterlet/clusterinfo/manager.go

Fixes: 
* https://issues.redhat.com/browse/ACM-7497: The agent on the hosting cluster continuously deletes the synced label claims that created by the customer hub.
* https://issues.redhat.com/browse/ACM-7500:  When rosa-logo configmap is created after agent pods started, it can't be detected as rosa.

Refactor: klusterlet claims

---

pkg/klusterlet/clusterinfo/distributionInfo_sync.go
pkg/klusterlet/clusterinfo/distributionInfo_sync_test.go

Fixes: https://issues.redhat.com/browse/ACM-7888
Also need to backport to 2.8.3.

Fix: distributionInfo miss sync for OSD type.

---

pkg/klusterlet/clusterinfo/defaultInfo_sync.go
pkg/klusterlet/clusterinfo/defaultInfo_sync_test.go

Ref: https://issues.redhat.com/browse/ACM-11167
Testing result:
On microshift
```
[root@rhel cloud-user]# oc get clusterclaim
NAME                                     AGE
id.k8s.io                                47m
kubeversion.open-cluster-management.io   47m
name                                     47m
platform.open-cluster-management.io      47m
product.open-cluster-management.io       47m
schedulable.open-cluster-management.io   47m
version.microshift.io                    47m
```
On hub
```
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
annotations:
open-cluster-management/created-via: other
...
labels:
cloud: Other
cluster.open-cluster-management.io/clusterset: default
clusterID: 0e581b5f-98e1-4a2a-9dc9-d9d555fd665c …
```

use id.k8s.io as MicroShift cluster ID

---

deploy/managedcluster/addons/install.sh

In quay.io  https://quay.io/repository/stolostron/cluster-proxy?tab=tags , I find the `latest` of cluster-proxy is the same with backplane-2.4 which is too old to use in e2e test.
So changed to use `main`.
Fixes: https://issues.redhat.com/browse/ACM-11089

Fix: e2e fail in get pod log, using `main` tag instead of `latest` of cluster-proxy images.

---

pkg/controllers/clusterset/clustersetmapper/clusterset_controller_test.go
pkg/controllers/clusterset/syncclusterrolebinding/syncclusterrolebinding_controller_test.go
pkg/controllers/clusterset/syncrolebinding/syncrolebinding_controller_test.go

In latest version of controller-runtime pkgs, when obj is not found, the result obj is not nil, so change to using err to determine the result to be more accurate.

Update using err not `obj == nil` to determine get result.

---

cmd/controller/controller.go
cmd/proxyserver/proxyserver.go
cmd/webhook/webhook.go

After go 1.20, this call is not nessary:
```
Deprecated: As of Go 1.20 there is no reason to call Seed with a random value. Programs that call Seed with a known value to get a specific sequence of results should use New(NewSource(seed)) to obtain a local random generator.
```

Remove depracated `randdom.Seed` function

---

pkg/controllers/clusterrole/clusterrole_controller.go
test/e2e/managedcluster_test.go

Stop adding managed cluster label for the namespace because import-controller already has [the same logic](https://github.com/stolostron/managedcluster-import-controller/blob/f9a6e8d5e9b9dec24eb2cd2129dacc30efb232a7/pkg/controller/managedcluster/managedcluster_controller.go#L98-L104)
Fix https://issues.redhat.com/browse/ACM-14616

🐛 Stop adding managed cluster label for the namespace

---

pkg/controllers/clusterrole/clusterrole_controller.go
pkg/controllers/clusterrole/clusterrole_controller_test.go

Related PR: https://github.com/stolostron/multicloud-operators-foundation/pull/781
Fixes: [ACM-15132](https://issues.redhat.com/browse/ACM-15132)
Test in the real env, the recreation doesn't happend, it's a miss piece in our code. 
Plan to be added in 2.13

Add clusterrole watch in clusterrole-controller

---

Makefile

The old `ensure-kustomize` does't support run e2e on macos:
```
curl -s -f -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.5.4/kustomize_v3.5.4_darwin_arm64.tar.gz -o '_output/tools/bin/kustomize_v3.5.4_darwin_arm64.tar.gz'
make: *** [ensure-kustomize] Error 56
```
The result of change:
```
➜  multicloud-operators-foundation git:(refactor-ensure-kustomize) make ensure-kustomize
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk:21: warning: overriding commands for target `ensure-imagebuilder'
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk:21: warning: ignoring old commands for target `ensure-imagebuilder'
Installing kustomize into '_output/tools/bin/kustomize-4.1.3'
mkdir -p …
```

Refactor: change to use the same kustomize as ocm and other repos do.

---

test/e2e/managedcluster_test.go
test/e2e/webhook_test.go

issue reference:
- https://github.com/stolostron/multicloud-operators-foundation/issues/684
- https://github.com/stolostron/multicloud-operators-foundation/issues/686

[bp-2.3] Comment out tests that may cause ocp api server to degrade

---

Dockerfile.rhtap

The go build uses rhel9 and the runtime tries to run it with rhel8 This results in errors running the binary due to glibc incompatible
Refs:
- https://issues.redhat.com/browse/ACM-20018

The konflux dockerfile has a mix or rhel9 and rhel8

---

.tekton/multicloud-manager-mce-29-pull-request.yaml
.tekton/multicloud-manager-mce-29-push.yaml

This PR adds multiarch build support to the Tekton pipeline configurations by enabling builds for multiple architectures: linux/x86_64, linux/arm64, linux/ppc64le, and linux/s390x. Changes include: - Updated build-platforms parameter in both push and pull request pipeline configurations - Added support for ARM64, PowerPC 64-bit LE, and IBM Z architectures - Maintained backward compatibility with existing x86_64 builds

Add multiarch build support to Tekton pipelines

---

pkg/controllers/clusterset/syncclusterrolebinding/syncclusterrolebinding_controller_test.go
pkg/controllers/clusterset/syncrolebinding/syncrolebinding_controller_test.go

This PR updates test files to use the new generic sets.Set[string] type instead of the legacy sets.String type. Changes include updating syncclusterrolebinding_controller_test.go and syncrolebinding_controller_test.go to use sets.Set[string], adding compatibility layer to convert between new and legacy set types, and removing unused newTestReconciler function. This change improves type safety and aligns with modern Go generics usage.

Update test files to use generic sets.Set[string] instead of legacy sets.String
